version: "2"
run:
  concurrency: 4
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - asasalint
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - dogsled
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - funlen
    - ginkgolinter
    - gocritic
    - gocyclo
    - gomoddirectives
    - gosec
    - govet
    - grouper
    - ineffassign
    - interfacebloat
    - misspell
    - mnd
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - prealloc
    - predeclared
    - promlinter
    - revive
    - sloglint
    - staticcheck
    - tagliatelle
    - testpackage
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
  settings:
    govet:
      enable-all: true
    nolintlint:
      require-explanation: true
      require-specific: true
    varnamelen:
      ignore-names:
        - l
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
