name: Build
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version:
          - "1.19.2"
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go_version }}
        uses: actions/setup-go@v4
        with:
          cache: true
          go-version: ${{ matrix.go_version }}

      - name: Tests
        run: go test -v ./...
