name: Tests

on:
  push:
  pull_request:

jobs:
  test-gomod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: go mod tidy && git diff --exit-code go.mod go.sum

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - run: make go-dependencies
      - run: make go-generate && git diff --exit-code
      - run: make go-all-tests

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "junit-report.xml"
        if: always()

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "junit-report.xml"
          verbose: true

      - name: Upload coverage reports to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage-unit.out
          verbose: true
