name: test Go using asdf

on:
  push:
  pull_request:

jobs:
  test-mod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - run: go mod tidy && git diff --exit-code go.mod go.sum

  test-asdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - run: go get -u golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest && go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest
      - run: go vet -vettool=$(which shadow) ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-pkg-cache: true

      - run: go get github.com/onsi/ginkgo/v2@latest && go install github.com/onsi/ginkgo/v2/ginkgo
      - run: $(go env GOPATH)/bin/ginkgo -r -race --cover --coverprofile=.coverage.out --junit-report=junit-report.xml ./...

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "junit-report.xml"
        if: always()

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.coverage.out
