name: test Go using asdf

on:
  push:
  pull_request:

jobs:
  test-mod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v2
      - run: go mod tidy && git diff --exit-code go.mod go.sum

  test-asdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v2

      - run: go get -u golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest && go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest
      - run: go vet -vettool=$(which shadow) ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-pkg-cache: true

      - run: go get github.com/onsi/ginkgo/v2@latest && go install github.com/onsi/ginkgo/v2/ginkgo
      - run: $(go env GOPATH)/bin/ginkgo --junit-report=report-ginkgo.xml ./...

      - run: go get -u gotest.tools/gotestsum@latest && go install gotest.tools/gotestsum@latest
      - run: $(go env GOPATH)/bin/gotestsum --junitfile report-testify.xml --format testname ./...

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "report-*.xml"
        if: always()
